[build]
  publish = "_site"
  command = "eleventy"
  functions = "functions"

[[plugins]]
  package = "@netlify/plugin-a11y"
  
  [plugins.inputs]
    # Check all HTML files in this project (the default behavior)
    # checkPaths = ['/']
    # Do not fail the build if a11y issues are found
    failWithIssues = false
    # Ignore all HTML files in listed directories
    ignoreDirectories = ['/admin']
    # Ignore any accessibility issues associated with an element matching this selector
    # ignoreElements = '.jumbotron > h2'
    # Ignore any accessibility issues associated with this rule code or type
    ignoreGuidelines = [
      'video-caption',
      'html-has-lang',
      'document-title',
      'color-contrast' # FIXME: color contrasts issues on political-plot
    ]
    # Perform a11y check against WCAG 2.1 AA
    wcagLevel = 'WCAG2AA'

# Only run in production as all generated img URls gives 404 on deploy-preview 
[[context.production.plugins]]
  package = "netlify-plugin-checklinks"

  [context.production.plugins.inputs]
    # An array of glob patterns for pages on your site
    # Recursive traversal will start from these
    entryPoints = [
      "*.html",
    ]

    # Recurse through all the links and asset references on your page, starting
    # at the entrypoints
    recursive = true

    # Checklinks outputs TAP (https://testanything.org/tap-version-13-specification.html)
    # by default. Enabling pretty mode makes the output easier on the eyes.
    pretty = true

    # You can mark some check as skipped, which will block checklinks
    # from ever attempting to execute them.
    # skipPatterns is an array of strings you can match against failing reports
    skipPatterns = [
      "_site/js-modules/",
      "D_Article_39",
      "politicalcompass.org",
      "tzitzimitl.net",
      # seems like cairn.fr disallow automated requests
      "https://www.cairn.info/revue-vingtieme-siecle-revue-d-histoire-2004-4-page-5.htm",
      "https://www.cairn.info/revue-migrations-societe-2007-2-page-141.htm",
      # checklinks doesn't correctly handle URL encoding for ids
      "Abolition_du_d%C3%A9cret_d'abolition_de_l'esclavage_du_16_pluvi%C3%B4se_an_II",
      # Timeout, but OK on 2022-11-27
      "https://web.archive.org/web/20110308070400/https://www.ldh-toulon.net/spip.php?article527"
    ]

    # You can mark some check as todo, which will execute the check, but allow failures.
    # todoPatterns is an array of strings you can match against failing reports
    todoPatterns = []

    # Report on all broken links to external pages.
    # Enabling this will make your tests more brittle, since you can't control
    # external pages.
    checkExternal = true

    # Enable to check references to source maps, source map sources etc.
    # Many build tools don't emit working references, so this is disabled by default
    followSourceMaps = true